# Generated by Django 4.1 on 2023-06-12 11:40

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wps.models
import wps.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("waterbody_code", models.CharField(max_length=32)),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Basin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="DischargePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("waterbody_code", models.CharField(max_length=32)),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GaugingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="NaceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="WaterFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterFlowNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterUseSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="WaterHeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("measured_on", models.DateTimeField()),
                (
                    "gauging_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_height_values",
                        to="wps.gaugingstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubBasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "basin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wps.basin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("validated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=128,
                    ),
                ),
                (
                    "water_type",
                    models.CharField(
                        choices=[
                            ("ground", "Ground water"),
                            ("surface", "Surface water"),
                        ],
                        default="surface",
                        max_length=128,
                    ),
                ),
                ("operator_name", models.CharField(max_length=128)),
                ("time_per_month", models.JSONField(blank=True, null=True)),
                ("abstraction_m3_per_month", models.JSONField(blank=True, null=True)),
                ("abstraction_m3s_per_month", models.JSONField(blank=True, null=True)),
                ("discharge_m3_per_month", models.JSONField(blank=True, null=True)),
                ("discharge_m3s_per_month", models.JSONField(blank=True, null=True)),
                ("ev1_per_month", models.JSONField(blank=True, null=True)),
                ("ev2_per_month", models.JSONField(blank=True, null=True)),
                ("ev3_per_month", models.JSONField(blank=True, null=True)),
                ("ev123_per_month", models.JSONField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=wps.utils.storage.DataStorage(),
                        upload_to=wps.models.get_permit_dir,
                    ),
                ),
                (
                    "abstraction_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permit_abstraction_points",
                        to="wps.abstractionpoint",
                    ),
                ),
                (
                    "discharge_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permit_discharge_points",
                        to="wps.dischargepoint",
                    ),
                ),
                (
                    "nace_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_permits",
                        to="wps.nacecode",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "water_use_sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sector_permits",
                        to="wps.waterusesector",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dischargepoint",
            name="subbasin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wps.subbasin",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("waterbody_code", models.CharField(max_length=32)),
                (
                    "subbasin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wps.subbasin",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="abstractionpoint",
            name="subbasin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wps.subbasin",
            ),
        ),
    ]
