# Generated by Django 4.1 on 2023-06-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0002_permit_remark_alter_permit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gaugingstation",
            name="altitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="gaugingstation",
            name="waterbody_code",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="permit",
            name="points_type",
            field=models.CharField(
                choices=[
                    ("abstraction", "Abstraction"),
                    ("discharge", "Discharge"),
                    ("combined", "Combined"),
                ],
                default="abstraction",
                max_length=128,
            ),
        ),
    ]
