# Generated by Django 4.1 on 2023-06-13 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0003_gaugingstation_altitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("wb_code", models.CharField(blank=True, max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
                (
                    "buffer200",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterFlowMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("measured_on", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Wetland",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="WaterFlowNetwork",
            new_name="WaterCourseNetwork",
        ),
        migrations.DeleteModel(
            name="WaterFlow",
        ),
        migrations.RemoveField(
            model_name="gaugingstation",
            name="waterbody_code",
        ),
        migrations.AddField(
            model_name="waterflowmeasurement",
            name="gauging_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_flow_values",
                to="wps.gaugingstation",
            ),
        ),
        migrations.AddField(
            model_name="abstractionpoint",
            name="water_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_abstraction_points",
                to="wps.watercourse",
            ),
        ),
        migrations.AddField(
            model_name="dischargepoint",
            name="water_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_discharge_points",
                to="wps.watercourse",
            ),
        ),
        migrations.AddField(
            model_name="gaugingstation",
            name="water_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_gauging_stations",
                to="wps.watercourse",
            ),
        ),
    ]
