# Generated by Django 4.1 on 2023-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0004_watercourse_waterflowmeasurement_wetland_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abstractionpoint",
            name="waterbody_code",
        ),
        migrations.RemoveField(
            model_name="assessmentpoint",
            name="waterbody_code",
        ),
        migrations.RemoveField(
            model_name="dischargepoint",
            name="waterbody_code",
        ),
    ]
