# Generated by Django 4.1 on 2023-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0005_remove_abstractionpoint_waterbody_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractionpoint",
            name="identifier",
            field=models.CharField(
                editable=False, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="assessmentpoint",
            name="identifier",
            field=models.CharField(
                editable=False, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="dischargepoint",
            name="identifier",
            field=models.CharField(
                editable=False, max_length=50, null=True, unique=True
            ),
        ),
    ]
