# Generated by Django 4.1 on 2023-06-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0006_abstractionpoint_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="water_use_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sector_permits",
                to="wps.waterusesector",
            ),
        ),
        migrations.CreateModel(
            name="DischargePointWaterUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("total_m3", models.FloatField()),
                ("avg_m3s", models.FloatField()),
                (
                    "discharge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ap_water_use",
                        to="wps.dischargepoint",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AbstractionPointWaterUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("total_m3", models.FloatField()),
                ("avg_m3s", models.FloatField()),
                (
                    "abstraction_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ap_water_use",
                        to="wps.abstractionpoint",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
