# Generated by Django 4.1 on 2023-06-15 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0007_alter_permit_water_use_sector_dischargepointwateruse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractionpointwateruse",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 15, 7, 48, 9, 569075, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dischargepointwateruse",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 15, 7, 48, 13, 173534, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
