# Generated by Django 4.1 on 2023-06-16 08:17

from django.db import migrations, models
import wps.validators


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0008_abstractionpointwateruse_added_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="abstraction_m3_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="abstraction_m3s_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="discharge_m3_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="discharge_m3s_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="ev123_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="ev1_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="ev2_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="ev3_per_month",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[wps.validators.validate_monthly_json_values],
            ),
        ),
    ]
