# Generated by Django 4.1 on 2023-06-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0009_alter_permit_abstraction_m3_per_month_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WaterCourse",
            new_name="SurfaceWaterBody",
        ),
        migrations.RenameField(
            model_name="abstractionpoint",
            old_name="water_course",
            new_name="water_body",
        ),
        migrations.RenameField(
            model_name="dischargepoint",
            old_name="water_course",
            new_name="water_body",
        ),
        migrations.RenameField(
            model_name="gaugingstation",
            old_name="water_course",
            new_name="water_body",
        ),
    ]
