# Generated by Django 4.1 on 2023-06-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0011_waterbodynode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeFlowMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("q50_value", models.FloatField()),
                ("ef_value", models.FloatField()),
                ("wafu_value", models.FloatField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_flow_values",
                        to="wps.waterbodynode",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WaterFlowMeasurement",
        ),
    ]
