# Generated by Django 4.1 on 2023-06-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0013_waterbodynode_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surfacewaterbody",
            name="node1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swb_nodes1",
                to="wps.waterbodynode",
            ),
        ),
        migrations.AlterField(
            model_name="surfacewaterbody",
            name="node2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swb_nodes2",
                to="wps.waterbodynode",
            ),
        ),
    ]
